<?php
// This file is part of Moodle - http://moodle.org/.

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_mcpcontent_create_label' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'create_label',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Create a label activity in a course section.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, moodle/course:manageactivities',
    ],
    'local_mcpcontent_create_page' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'create_page',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Create a page resource in a course section.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, moodle/course:manageactivities',
    ],
    'local_mcpcontent_create_url' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'create_url',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Create a URL resource in a course section.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, moodle/course:manageactivities',
    ],
    'local_mcpcontent_create_quiz' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'create_quiz',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Create a quiz activity with description, timer, attempts and grade-to-pass settings.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, moodle/course:manageactivities, mod/quiz:addinstance',
    ],
    'local_mcpcontent_update_quiz_settings' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'update_quiz_settings',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Update quiz description, timer, attempts, visibility and grade-to-pass settings.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, moodle/course:manageactivities, mod/quiz:addinstance',
    ],
    'local_mcpcontent_create_question_category' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'create_question_category',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Create a question category in a course question bank.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, moodle/question:add',
    ],
    'local_mcpcontent_create_multichoice_question' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'create_multichoice_question',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Create a multiple-choice question and optionally add it to a quiz.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, moodle/question:add',
    ],
    'local_mcpcontent_create_truefalse_question' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'create_truefalse_question',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Create a true/false question and optionally add it to a quiz.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, moodle/question:add',
    ],
    'local_mcpcontent_create_shortanswer_question' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'create_shortanswer_question',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Create a short-answer question and optionally add it to a quiz.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, moodle/question:add',
    ],
    'local_mcpcontent_add_question_to_quiz' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'add_question_to_quiz',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Add an existing question to a quiz.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, mod/quiz:manage',
    ],
    'local_mcpcontent_update_sections' => [
        'classname' => 'local_mcpcontent_external',
        'methodname' => 'update_sections',
        'classpath' => 'local/mcpcontent/externallib.php',
        'description' => 'Update course section names and summaries.',
        'type' => 'write',
        'capabilities' => 'local/mcpcontent:createcontent, moodle/course:update',
    ],
];
